# GRAMMAR
hálfur = "[nl]ke[n]-?((g?s?)|([svo]?[fme]?))"
hálfan = "[nl]ke[o]-?((g?s?)|([svo]?[fme]?))"
hálfum = "[nl][kvh][ef]þ-?((g?s?)|([svo]?[fme]?))"
hálfs = "[nl][kh]ee-?((g?s?)|([svo]?[fme]?))"
hálf = "(([nl]ven)|([n|l]hf[n|o]))-?((g?s?)|([svo]?[fme]?))"
hálfa = "[nl][k|v][f|e]o-?((g?s?)|([svo]?[fme]?))"
hálfri = "[nl]veþ-?((g?s?)|([svo]?[fme]?))"
hálfrar = "[nl]vee-?((g?s?)|([svo]?[fme]?))"
hálft = "[nl]he[n|o]-?((g?s?)|([svo]?[fme]?))"
hálfu = "[nl]heþ-?((g?s?)|([svo]?[fme]?))"
hálfir = "[nl]kfn-?((g?s?)|([svo]?[fme]?))"
hálfa = "[nl][k|v][f|e]o-?((g?s?)|([svo]?[fme]?))"
hálfra = "[nl][k|v|h]fe-?((g?s?)|([svo]?[fme]?))"
hálfar = "[nl]vf[n|o]-?((g?s?)|([svo]?[fme]?))"

einn = "[nl]k[ef][no]-?((g?s?)|([svo]?[fme]?))"
einum = "[nl]k[ef]þ-?((g?s?)|([svo]?[fme]?))"
eins = "[nl][kh][ef]e-?((g?s?)|([svo]?[fme]?))"
ein = "(([nl]v[ef]n)|([n|l]hf[n|o]))-?((g?s?)|([svo]?[fme]?))"
eina = "[nl]v[ef]o-?((g?s?)|([svo]?[fme]?))"
einni = "[nl]v[ef]þ-?((g?s?)|([svo]?[fme]?))"
einnar = "[nl]v[ef]e-?((g?s?)|([svo]?[fme]?))"
eitt = "[nl]h[ef][no]-?((g?s?)|([svo]?[fme]?))"
einu = "[nl]h[ef]þ-?((g?s?)|([svo]?[fme]?))"

tveir = "[nl]k[ef]n-?((g?s?)|([svo]?[fme]?))"
tvo = "[nl]k[ef]o-?((g?s?)|([svo]?[fme]?))"
tveimur = "[nl][kvh][ef]þ-?((g?s?)|([svo]?[fme]?))"
tveggja = "[nl][kvh][ef]e-?((g?s?)|([svo]?[fme]?))"
tvær = "[nl]v[ef][no]-?((g?s?)|([svo]?[fme]?))"
tvö = "[nl]h[ef][no]-?((g?s?)|([svo]?[fme]?))"

þrír = "[nl]k[ef]n-?((g?s?)|([svo]?[fme]?))"
þrjá = "[nl]k[ef]o-?((g?s?)|([svo]?[fme]?))"
þremur = "[nl][kvh][ef]þ-?((g?s?)|([svo]?[fme]?))"
þriggja = "[nl][kvh][ef]e-?((g?s?)|([svo]?[fme]?))"
þrjár = "[nl]v[ef][no]-?((g?s?)|([svo]?[fme]?))"
þrjú = "[nl]h[ef][no]-?((g?s?)|([svo]?[fme]?))"

fjórir = "[nl]k[ef]n-?((g?s?)|([svo]?[fme]?))"
fjóra = "[nl]k[ef]o-?((g?s?)|([svo]?[fme]?))"
fjórum = "[nl][kvh][ef]þ-?((g?s?)|([svo]?[fme]?))"
fjögurra = "[nl][kvh][ef]e-?((g?s?)|([svo]?[fme]?))"
fjórar = "[nl]v[ef][no]-?((g?s?)|([svo]?[fme]?))"
fjögur = "[nl]h[ef][no]-?((g?s?)|([svo]?[fme]?))"

nonoun = "^(?![nl][kvh][ef][noþe]-?((g?s?)|([svo]?[fme]?)))[a-záðéíóúýþæö\d\-]+$"

annar = r"[nl]ken-?(g?s?|[svo]?[fme]?)"
annan = r"[nl]keo-?(g?s?|[svo]?[fme]?)"
öðrum = r"[nl]((ke)|([kvh]f))þ-?(g?s?|[svo]?[fme]?)"
annars = r"[nl]kee-?(g?s?|[svo]?[fme]?)"
aðrir = r"[nl]kfn-?(g?s?|[svo]?[fme]?)"
aðra = r"[nl](kf|ve)o-?((g?s?)|([svo]?[fme]?))"
annarra = r"[nl][kvh]fe-?(g?s?|[svo]?[fme]?)"
önnur = r"[nl](ven|hf[no])-?(g?s?|[svo]?[fme]?)"
annarri = r"[nl]veþ-?(g?s?|[svo]?[fme]?)"
annarrar = r"[nl]vee-?(g?s?|[svo]?[fme]?)"
aðrar = r"[nl]vf[no]-?(g?s?|[svo]?[fme]?)"
annað = r"[nl]he[no]-?(g?s?|[svo]?[fme]?)"
öðru = r"[nl]heþ-?(g?s?|[svo]?[fme]?)"
annars = r"[nl][kh]ee-?(g?s?|[svo]?[fme]?)"

fyrsti = r"[nl]ken-?(g?s?|[svo]?[fme]?)"
fyrsta = r"[nl](ke[oþe]|ven|he[noþe])-?(g?s?|[svo]?[fme]?)"
fyrstu = r"[nl](([kvh]f[noþe])|(ve[oþe]))-?(g?s?|[svo]?[fme]?)"

# RULES

zeropnt_ptrn = "^(([1-9]((\d{0,2}(\.\d{3})*\.)\d{3}))|\d+|0),"
tns_ptrn = "^((([1-9]((\d{0,2}(\.\d{3})*\.)|\d*))\d)|[1-9])?"
dec_ptrn = "((,\d*)|(\s1\/2|\s?½))?$"
dec_ptrn_def = "(,\d*)|(\s1\/2|\s?½)$"
dec_ptrn_ordinal = "(\.|(,\d*)|(\s1\/2|\s?½))?$"

ones_ptrn_no11 = "^((([1-9]((\d{0,2}(\.\d{3})*\.\d)|\d*))[02-9])|[2-9]?)?"
hndrds_ptrn_no11 = "^([1-9]((\d{0,2}(\.\d{3})*\.)|\d*))?"
hndrds_ptrn_no11_def = "^([1-9]((\d{0,2}(\.\d{3})*\.)|\d*))"

ones_ptrn_11 = "^([1-9]((\d{0,2}(\.\d{3})*\.\d{2}|\d*))|[1-9]?)?"
hndrds_ptrn_11 = "^((([1-9]((\d{0,2}(\.\d{3})*\.)|\d*)))|[1-9]?)"

half_ptrn = "^(([1-9]((\d{0,2}(\.\d{3})*))|\d+))\s?(1\/2|½)$"
fraction_ptrn_before = "^(([1-9]((\d{0,2}(\.\d{3})*))|\d+))\s"
thsnds_ptrn_after = "(\.?(000|(0[2-9][1-9])|([1-9](?!00)\d{2})))"
thsnds_and_ptrn_cardinal = "\.?(0([01][1-9]|[1-9]0)|[1-9]00)"
thsnds_and_ptrn_ordinal = "\.?(0[2-9]0|[1-9]00)\.$"

hndrds_ptrn_after = "(0([01][1-9]|[2-9]0))|([1-9]00)"
hndrd_thsnd_after = "([2-9][1-9])(\.?\d{3})"
hndrd_and_thsnd = "(([01][1-9]\.?\d{3})|([2-9]0\.?\d{3}))"

million_and_cardinal = "\.(([1-9]00\.000)|(0[1-9]0\.000)|(00[1-9]\.000)|(000\.[1-9]00)|(000\.0([01][1-9]|[2-9]0)))"
million_and_ordinal = "\.(([1-9]00\.000)|(0[1-9]0\.000)|(00[1-9]\.000)|(000\.[1-9]00)|(000\.0[2-9]0))\.$"
milln_ptrn_after = "\.((000\.000)|([1-9](?!00\.000)\d{2}\.\d{3})|(0[1-9](?!0\.000)\d\.\d{3})|(00[1-9]\.(?!0{3})\d{3})|(0{3}\.0[2-9][1-9]))"
hndrd_and_million = "([01][1-9]|[2-9]0)(\.\d{3}){2}"
hndrd_million = "([2-9][1-9])(\.\d{3}){2}"

billion_and_cardinal = "\.((([1-9]00)|(0[1-9]0)|(00[1-9]))(\.0{3}){2}|(0{3}\.([1-9]00|0[1-9]0|00[1-9])\.0{3})|((0{3}\.){2}([1-9]00|0[1-9]0|0[01][1-9])))"
billion_and_ordinal = "\.((([1-9]00)|(0[1-9]0)|(00[1-9]))(\.0{3}){2}|(0{3}\.([1-9]00|0[1-9]0|00[1-9])\.0{3})|((0{3}\.){2}([1-9]00|0[1-9]0)|10))\.$"
billion1 = "([1-9](?!00(\.000){2})\d{2}(\.\d{3}){2})"
billion2 = "(0[1-9](?!0(\.000){2})\d(\.\d{3}){2})"
billion3 = "(00[1-9](?!(\.000){2})(\.\d{3}){2})"
billion4 = "(0{3}\.[1-9](?!00\.000)\d{2}\.\d{3})"
billion5 = "(0{3}\.0[1-9](?!0\.000)\d\.\d{3})"
billion6 = "(0{3}\.00[1-9]\.(?!000)\d{3})"
billion7 = "((0{3}\.){2}[1-9](?!00)\d{2})"
billion8 = "((0{3}\.){2}0[2-9][1-9])"

billion_after = "\.((000(\.0{3}){2})|" + billion1 + "|" + billion2 + "|" + billion3 + "|" + billion4 + "|" + billion5 + "|" + billion6 + "|" + billion7 + "|" + billion8 + ")"

hndrd_and_billion = "([01][1-9]|[2-9]0)(\.\d{3}){3}"
hndrd_billion = "([2-9][1-9])(\.\d{3}){3}"