# GRAMMAR
hálfur = r"[nl]ke[n]-?((g?s?)|([svo]?[fme]?))"
hálfan = r"[nl]ke[o]-?((g?s?)|([svo]?[fme]?))"
hálfum = r"[nl][kvh][ef]þ-?((g?s?)|([svo]?[fme]?))"
hálfs = r"[nl][kh]ee-?((g?s?)|([svo]?[fme]?))"
hálf = r"(([nl]ven)|([n|l]hf[n|o]))-?((g?s?)|([svo]?[fme]?))"
hálfa = r"[nl][k|v][f|e]o-?((g?s?)|([svo]?[fme]?))"
hálfri = r"[nl]veþ-?((g?s?)|([svo]?[fme]?))"
hálfrar = r"[nl]vee-?((g?s?)|([svo]?[fme]?))"
hálft = r"[nl]he[n|o]-?((g?s?)|([svo]?[fme]?))"
hálfu = r"[nl]heþ-?((g?s?)|([svo]?[fme]?))"
hálfir = r"[nl]kfn-?((g?s?)|([svo]?[fme]?))"
hálfa = r"[nl][k|v][f|e]o-?((g?s?)|([svo]?[fme]?))"
hálfra = r"[nl][k|v|h]fe-?((g?s?)|([svo]?[fme]?))"
hálfar = r"[nl]vf[n|o]-?((g?s?)|([svo]?[fme]?))"

fractionnom = r"[nl][kvh][ef]n-?((g?s?)|([svo]?[fme]?))"
fractiondat = r"[nl][kvh][ef]o-?((g?s?)|([svo]?[fme]?))"
fractionacc = r"[nl][kvh][ef]þ-?((g?s?)|([svo]?[fme]?))"
fractiongen = r"[nl][kvh][ef]e-?((g?s?)|([svo]?[fme]?))"

einn = r"[nl]k[ef][no]-?((g?s?)|([svo]?[fme]?))"
einum = r"[nl]k[ef]þ-?((g?s?)|([svo]?[fme]?))"
eins = r"[nl][kh][ef]e-?((g?s?)|([svo]?[fme]?))"
ein = r"(([nl]v[ef]n)|([n|l]hf[n|o]))-?((g?s?)|([svo]?[fme]?))"
eina = r"[nl]v[ef]o-?((g?s?)|([svo]?[fme]?))"
einni = r"[nl]v[ef]þ-?((g?s?)|([svo]?[fme]?))"
einnar = r"[nl]v[ef]e-?((g?s?)|([svo]?[fme]?))"
eitt = r"[nl]h[ef][no]-?((g?s?)|([svo]?[fme]?))"
einu = r"[nl]h[ef]þ-?((g?s?)|([svo]?[fme]?))"

tveir = r"[nl]k[ef]n-?((g?s?)|([svo]?[fme]?))"
tvo = r"[nl]k[ef]o-?((g?s?)|([svo]?[fme]?))"
tveimur = r"[nl][kvh][ef]þ-?((g?s?)|([svo]?[fme]?))"
tveggja = r"[nl][kvh][ef]e-?((g?s?)|([svo]?[fme]?))"
tvær = r"[nl]v[ef][no]-?((g?s?)|([svo]?[fme]?))"
tvö = r"[nl]h[ef][no]-?((g?s?)|([svo]?[fme]?))"

þrír = r"[nl]k[ef]n-?((g?s?)|([svo]?[fme]?))"
þrjá = r"[nl]k[ef]o-?((g?s?)|([svo]?[fme]?))"
þremur = r"[nl][kvh][ef]þ-?((g?s?)|([svo]?[fme]?))"
þriggja = r"[nl][kvh][ef]e-?((g?s?)|([svo]?[fme]?))"
þrjár = r"[nl]v[ef][no]-?((g?s?)|([svo]?[fme]?))"
þrjú = r"[nl]h[ef][no]-?((g?s?)|([svo]?[fme]?))"

fjórir = r"[nl]k[ef]n-?((g?s?)|([svo]?[fme]?))"
fjóra = r"[nl]k[ef]o-?((g?s?)|([svo]?[fme]?))"
fjórum = r"[nl][kvh][ef]þ-?((g?s?)|([svo]?[fme]?))"
fjögurra = r"[nl][kvh][ef]e-?((g?s?)|([svo]?[fme]?))"
fjórar = r"[nl]v[ef][no]-?((g?s?)|([svo]?[fme]?))"
fjögur = r"[nl]h[ef][no]-?((g?s?)|([svo]?[fme]?))"

nonoun = r"^(?![nl][kvh][ef][noþe]-?((g?s?)|([svo]?[fme]?)))[a-záðéíóúýþæö\d\-]+$"

annar = r"[nl]ken-?(g?s?|[svo]?[fme]?)"
annan = r"[nl]keo-?(g?s?|[svo]?[fme]?)"
öðrum = r"[nl]((ke)|([kvh]f))þ-?(g?s?|[svo]?[fme]?)"
annars = r"[nl]kee-?(g?s?|[svo]?[fme]?)"
aðrir = r"[nl]kfn-?(g?s?|[svo]?[fme]?)"
aðra = r"[nl](kf|ve)o-?((g?s?)|([svo]?[fme]?))"
annarra = r"[nl][kvh]fe-?(g?s?|[svo]?[fme]?)"
önnur = r"[nl](ven|hf[no])-?(g?s?|[svo]?[fme]?)"
annarri = r"[nl]veþ-?(g?s?|[svo]?[fme]?)"
annarrar = r"[nl]vee-?(g?s?|[svo]?[fme]?)"
aðrar = r"[nl]vf[no]-?(g?s?|[svo]?[fme]?)"
annað = r"[nl]he[no]-?(g?s?|[svo]?[fme]?)"
öðru = r"[nl]heþ-?(g?s?|[svo]?[fme]?)"
annars = r"[nl][kh]ee-?(g?s?|[svo]?[fme]?)"

fyrsti = r"[nl]ken-?(g?s?|[svo]?[fme]?)"
fyrsta = r"[nl](ke[oþe]|ven|he[noþe])-?(g?s?|[svo]?[fme]?)"
fyrstu = r"[nl](([kvh]f[noþe])|(ve[oþe]))-?(g?s?|[svo]?[fme]?)"

# RULES

zeropnt_ptrn = r"^(([1-9]((\d{0,2}(\.\d{3})*\.)\d{3}))|\d+|0),"
tns_ptrn = r"^((([1-9]((\d{0,2}(\.\d{3})*\.)|\d*))\d)|[1-9])?"
dec_ptrn = r"((,\d*)|(\s1\/2|\s?(½|⅓|¼|⅔|¾)))?$"
dec_ptrn_def = r"(,\d*)|(\s1\/2|\s?(½|⅓|¼|⅔|¾))$"
dec_ptrn_ordinal = r"(\.|(,\d*)|(\s1\/2|\s?(½|⅓|¼|⅔|¾)))?$"

ones_ptrn_no11 = r"^((([1-9]((\d{0,2}(\.\d{3})*\.\d)|\d*))[02-9])|[2-9]?)?"
hndrds_ptrn_no11 = r"^([1-9]((\d{0,2}(\.\d{3})*\.)|\d*))?"
hndrds_ptrn_no11_def = r"^([1-9]((\d{0,2}(\.\d{3})*\.)|\d*))"

ones_ptrn_11 = r"^([1-9]((\d{0,2}(\.\d{3})*\.\d{2}|\d*))|[1-9]?)?"
hndrds_ptrn_11 = r"^((([1-9]((\d{0,2}(\.\d{3})*\.)|\d*)))|[1-9]?)"

#half_ptrn = r"^(([1-9]((\d{0,2}(\.\d{3})*))|\d+))\s?(1\/2|½)$"
fraction_ptrn_before = r"^(([1-9]((\d{0,2}(\.\d{3})*))|\d+))\s"
thsnds_ptrn_after = r"(\.?(000|(0[2-9][1-9])|([1-9](?!00)\d{2})))"
thsnds_and_ptrn_cardinal = r"\.?(0([01][1-9]|[1-9]0)|[1-9]00)"
thsnds_and_ptrn_ordinal = r"\.?(0[2-9]0|[1-9]00)\.$"

hndrds_ptrn_after = r"(0([01][1-9]|[2-9]0))|([1-9]00)"
hndrd_thsnd_after = r"([2-9][1-9])(\.?\d{3})"
hndrd_and_thsnd = r"(([01][1-9]\.?\d{3})|([2-9]0\.?\d{3}))"

million_and_cardinal = r"\.(([1-9]00\.000)|(0[1-9]0\.000)|(00[1-9]\.000)|(000\.[1-9]00)|(000\.0([01][1-9]|[2-9]0)))"
million_and_ordinal = r"\.(([1-9]00\.000)|(0[1-9]0\.000)|(00[1-9]\.000)|(000\.[1-9]00)|(000\.0[2-9]0))\.$"
milln_ptrn_after = r"\.((000\.000)|([1-9](?!00\.000)\d{2}\.\d{3})|(0[1-9](?!0\.000)\d\.\d{3})|(00[1-9]\.(?!0{3})\d{3})|(0{3}\.0[2-9][1-9]))"
hndrd_and_million = r"([01][1-9]|[2-9]0)(\.\d{3}){2}"
hndrd_million = r"([2-9][1-9])(\.\d{3}){2}"

billion_and_cardinal = r"\.((([1-9]00)|(0[1-9]0)|(00[1-9]))(\.0{3}){2}|(0{3}\.([1-9]00|0[1-9]0|00[1-9])\.0{3})|((0{3}\.){2}([1-9]00|0[1-9]0|0[01][1-9])))"
billion_and_ordinal = r"\.((([1-9]00)|(0[1-9]0)|(00[1-9]))(\.0{3}){2}|(0{3}\.([1-9]00|0[1-9]0|00[1-9])\.0{3})|((0{3}\.){2}([1-9]00|0[1-9]0)|10))\.$"
billion1 = r"([1-9](?!00(\.000){2})\d{2}(\.\d{3}){2})"
billion2 = r"(0[1-9](?!0(\.000){2})\d(\.\d{3}){2})"
billion3 = r"(00[1-9](?!(\.000){2})(\.\d{3}){2})"
billion4 = r"(0{3}\.[1-9](?!00\.000)\d{2}\.\d{3})"
billion5 = r"(0{3}\.0[1-9](?!0\.000)\d\.\d{3})"
billion6 = r"(0{3}\.00[1-9]\.(?!000)\d{3})"
billion7 = r"((0{3}\.){2}[1-9](?!00)\d{2})"
billion8 = r"((0{3}\.){2}0[2-9][1-9])"

billion_after = r"\.((000(\.0{3}){2})|" + billion1 + "|" + billion2 + "|" + billion3 + "|" + billion4 + "|" + billion5 + "|" + billion6 + "|" + billion7 + "|" + billion8 + ")"

hndrd_and_billion = r"([01][1-9]|[2-9]0)(\.\d{3}){3}"
hndrd_billion = r"([2-9][1-9])(\.\d{3}){3}"