symb_dict = {"&": "og",
        "/": " skástrik ",
        "\+": " plús ",
        "=": " jafnt og ",
        "≠": " ekki jafnt og ",
        "ε": " epsilon ",
        r"^\±|\∓$": " plús mínus ",
        r"^\~|\≈$": " um það bil ",
        "→": " þar af leiðandi ",
        "≡": " skilgreint sem" ,
        " < ": " minna en ",
        " > ": " stærra en ",
        "≤": " minna en eða jafnt og ",
        "≥": " stærra en eða jafnt og ",
        "∞": " óendanlegt ",
        "°": " gráður ",
        r"^(Α|α)$": " alfa",
        r"^(Β|β)$": " beta",
        r"^(Γ|γ)$": " gamma",
        r"^(Δ|δ)$": " delta",
        r"^(Ε|ε)$": " epsilon",
        r"^(Ζ|ζ)$": " zeta",
        r"^(Η|η)$": " eta",
        r"^(Θ|θ)$": " þeta",
        r"^(Ι|ι)$": " jóta",
        r"^(Κ|κ)$": " kappa",
        r"^(Λ|λ)$": " lambda",
        r"^(Μ|μ)$": " mý",
        r"^(Ν|ν)$": " ný",
        r"^(Ξ|ξ)$": " xí",
        r"^(Ο|ο)$": " ómíkrón",
        r"^(Π π)$": " pí",
        r"^(Ρ|ρ)$": " hró",
        r"^(Σ|σ)$": " sigma",
        r"^(Τ|τ)$": " tá",
        r"^(Υ|υ)$": " upsílon",
        r"^(Φ|φ)$": " fí",
        r"^(Χ|χ)$": " kí",
        r"^(Ψ|ψ)$": " psí",
        r"^(Ω|ω)$": " ómega"}



