direction_dict = {'(\W|^)(SV(\-|–|—))(?!(til|lands|átt|verðu|vert))([A-ZÁÐÉÍÓÚÝÞÆÖa-záðéíóúýþæö]+)(\W|$)': '\g<1>suðvestur\g<3>\g<4>\g<5>',
					'(\W|^)(NV(\-|–|—))(?!(til|lands|átt|verðu|vert))([A-ZÁÐÉÍÓÚÝÞÆÖa-záðéíóúýþæö]+)(\W|$)': '\g<1>norðvestur\g<3>\g<4>\g<5>',
					'(\W|^)(NA(\-|–|—))(?!(til|lands|átt|verðu|vert))([A-ZÁÐÉÍÓÚÝÞÆÖa-záðéíóúýþæö]+)(\W|$)': '\g<1>norðaustur\g<3>\g<4>\g<5>',
					'(\W|^)(SA(\-|–|—))(?!(til|lands|átt|verðu|vert))([A-ZÁÐÉÍÓÚÝÞÆÖa-záðéíóúýþæö]+)(\W|$)': '\g<1>suðaustur\g<3>\g<4>\g<5>',
					'(\W|^)(A(\-|–|—))([A-ZÁÐÉÍÓÚÝÞÆÖa-záðéíóúýþæö]*sýsl[ua])(\W|$)': '\g<1>austur\g<3>\g<4>\g<5>',
					'(\W|^)(S(\-|–|—))([A-ZÁÐÉÍÓÚÝÞÆÖa-záðéíóúýþæö]*sýsl[ua])(\W|$)': '\g<1>suður\g<3>\g<4>\g<5>',
					'(\W|^)(V(\-|–|—))([A-ZÁÐÉÍÓÚÝÞÆÖa-záðéíóúýþæö]*sýsl[ua])(\W|$)': '\g<1>vestur\g<3>\g<4>\g<5>',
					'(\W|^)(N(\-|–|—))([A-ZÁÐÉÍÓÚÝÞÆÖa-záðéíóúýþæö]*sýsl[ua])(\W|$)': '\g<1>norður\g<3>\g<4>\g<5>',
					'(\W|^)(SV(\-|–|—))(lands|átt|verðu|vert)(\W|$)': '\g<1>suðvestan\g<4>\g<5>',
					'(\W|^)(V(\-|–|—))(lands|átt|verðu|vert)(\W|$)': '\g<1>vestan\g<4>\g<5>',
					'(\W|^)(NV(\-|–|—))(lands|átt|verðu|vert)(\W|$)': '\g<1>norðvestan\g<4>\g<5>',
					'(\W|^)(N(\-|–|—))(lands|átt|verðu|vert)(\W|$)': '\g<1>norðan\g<4>\g<5>',
					'(\W|^)(NA(\-|–|—))(lands|átt|verðu|vert)(\W|$)': '\g<1>norðaustan\g<4>\g<5>',
					'(\W|^)(A(\-|–|—))(lands|átt|verðu|vert)(\W|$)': '\g<1>austan\g<4>\g<5>',
					'(\W|^)(SA(\-|–|—))(lands|átt|verðu|vert)(\W|$)': '\g<1>suðaustan\g<4>\g<5>',
					'(\W|^)(S(\-|–|—))(lands|átt|verðu|vert)(\W|$)': '\g<1>sunnan\g<4>\g<5>',
					'(\W|^)(V(\-|–|—))(landi?)(\W|$)': '\g<1>vestur\g<4>\g<5>',
					'(\W|^)(N(\-|–|—))(landi?)(\W|$)': '\g<1>norður\g<4>\g<5>',
					'(\W|^)(A(\-|–|—))(landi?)(\W|$)': '\g<1>austur\g<4>\g<5>',
					'(\W|^)(S(\-|–|—))(landi?)(\W|$)': '\g<1>suður\g<4>\g<5>',
					'(\W|^)(SV(\-|–|—))(til)(\W|$)': '\g<1>suðvestan \g<4>\g<5>',
					'(\W|^)(V(\-|–|—))(til)(\W|$)': '\g<1>vestan \g<4>\g<5>',
					'(\W|^)(NV(\-|–|—))(til)(\W|$)': '\g<1>norðvestan \g<4>\g<5>',
					'(\W|^)(N(\-|–|—))(til)(\W|$)': '\g<1>norðan \g<4>\g<5>',
					'(\W|^)(NA(\-|–|—))(til)(\W|$)': '\g<1>norðaustan \g<4>\g<5>',
					'(\W|^)(A(\-|–|—))(til)(\W|$)': '\g<1>austan \g<4>\g<5>',
					'(\W|^)(SA(\-|–|—))(til)(\W|$)': '\g<1>suðaustan \g<4>\g<5>',
					'(\W|^)(S(\-|–|—))(til)(\W|$)': '\g<1>sunnan \g<4>\g<5>'}